const PERMISSIONS = Object.freeze({

    // Dashboard
    VIEW_DASHBOARD: "VIEW_DASHBOARD",

    // Employee
    CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
    VIEW_EMPLOYEE: "VIEW_EMPLOYEE",
    UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
    DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
    RESTORE_EMPLOYEE: "RESTORE_EMPLOYEE",

    // Lead
    CREATE_LEAD: "CREATE_LEAD",
    VIEW_LEAD: "VIEW_LEAD",
    UPDATE_LEAD: "UPDATE_LEAD",
    DELETE_LEAD: "DELETE_LEAD",
    ASSIGN_LEAD: "ASSIGN_LEAD",

    // Followup
    CREATE_FOLLOWUP: "CREATE_FOLLOWUP",
    VIEW_FOLLOWUP: "VIEW_FOLLOWUP",
    UPDATE_FOLLOWUP: "UPDATE_FOLLOWUP",
    DELETE_FOLLOWUP: "DELETE_FOLLOWUP",
    COMPLETE_FOLLOWUP: "COMPLETE_FOLLOWUP",
    RESTORE_FOLLOWUP: "RESTORE_FOLLOWUP",

    // Course
    CREATE_COURSE: "CREATE_COURSE",
    VIEW_COURSE: "VIEW_COURSE",
    UPDATE_COURSE: "UPDATE_COURSE",
    DELETE_COURSE: "DELETE_COURSE",

    // Department
    CREATE_DEPARTMENT: "CREATE_DEPARTMENT",
    VIEW_DEPARTMENT: "VIEW_DEPARTMENT",
    UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",
    DELETE_DEPARTMENT: "DELETE_DEPARTMENT",

});

export default PERMISSIONS;