/**
 * =====================================================
 * Lead Timeline Activity Types
 * =====================================================
 */

export const TIMELINE_ACTIVITY = {
  LEAD_CREATED: "LEAD_CREATED",
  LEAD_UPDATED: "LEAD_UPDATED",
  LEAD_ASSIGNED: "LEAD_ASSIGNED",

  STATUS_CHANGED: "STATUS_CHANGED",

  FOLLOWUP_CREATED: "FOLLOWUP_CREATED",
  FOLLOWUP_COMPLETED: "FOLLOWUP_COMPLETED",

  NOTE_ADDED: "NOTE_ADDED",

  ADMISSION_COMPLETED: "ADMISSION_COMPLETED",

  STUDENT_CREATED: "STUDENT_CREATED",

  COURSE_CHANGED: "COURSE_CHANGED",

  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",

  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
};

export default TIMELINE_ACTIVITY;